### ISSUE TITLE
Task-Like AsyncEnumerable

### ISSUE THREAD

**Issue by Andrew-Hanlon** [tyrotoxin/AsyncEnumerable#13]
Hi there, I just came across your library yesterday, and it seems great! I thought you might be interested in an experiment I put together recently to create a [task-like AsyncEnumerable](https://github.com/Andrew-Hanlon/AsyncEnumerator) using C# 7's new features. I believe there could be some real synergy in our approaches. Please reach out if interested, as I would be very keen to discuss async sequences!

**Comment by tyrotoxin** [comment]
Hi @Andrew-Hanlon, that can be interesting, but I'm hesitant to add more features, because they promised to deliver language-integrated async enumeration in C# 8. Maybe we should just wait :)

**Comment by tyrotoxin** [comment]
I apologize, but I'm currently working on a much more exciting project, so I will not have any additional free time available to invest into advanced features of async enumeration, but you are welcome to use pieces of this library in your project or contribute back if needed.

**Comment by Andrew-Hanlon** [comment]
Hey Serge, not to worry at all. Look forward to reading about the new exciting project. I'll post here if I follow up with any additional async sequence work. Cheers.

**Comment by tyrotoxin** [comment]
Sounds good, thanks
