### ISSUE TITLE
Enumerate an AsyncEnumerable with some degree of parallelism

### ISSUE THREAD

**Issue by Telavian** [tyrotoxin/AsyncEnumerable#6]
I first want to mention that you library is great. I think something like this should have been part of the framework, because it makes perfect sense with the shift to async/await.

As an enumerable things are working great. The only thing I have noticed is that enumerating the entire sequence can take a long time because of one async call after another.

Would it be possible to prefetch a call for a certain amount in order to save time. I am working on something, but wondered if you had any ideas.

I would imagine I could execute the [calls in batches](http://stackoverflow.com/questions/10806951/how-to-limit-the-amount-of-concurrent-async-i-o-operations) however that would seem to negate the advantages of an async enumerable.

**Comment by tyrotoxin** [comment]
Thanks! I submitted a [feature request](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/12338136-add-async-foreach-to-c-and-iasyncenumerator-to-n) to Microsoft long time ago - hope they'll pay attention to it one day.

What version of AsyncEnumerator do you use? I did huge performance improvement in the version 1.3.0, and now it works about 5 times faster compared to previous versions.

It depends on your scenario, but call in batches only beneficial when the underlying async call (inside the enumerator) supports batching. For instance, like Azure Storage Queue or Azure Storage Table support batch operations, so you send only 1 request (the underlying async call) but get back multiple results, which you iterate through synchronously even though you type `await yield.ReturnAsync()`. Such approach gives the best performance.

**Comment by Telavian** [comment]
I am using the latest version on nuget as of today.

The main thing is I am essentially flattening about 1000 calls into one
async IEnumerable steam using your library. It is certainly as fast as the
underlying async calls there is no doubt.
However if you have X async calls and each take Y ms then the total time
will be X*Y ms.

With prefetch this would be faster.

**Comment by tyrotoxin** [comment]
It would be helpful if you provide a sample code. Do you use `ForEachAsync` or `ParallelForEachAsync`?

**Comment by Telavian** [comment]
No. Maybe those would be helpful.

I essentially just want to perform multiple concatenation of async calls. It seems the AsyncEnumerable class can perform this.

I have an extension method I use as follows:

```
        public static async Task<IEnumerable<TResult>> SelectAsync<TItem, TResult>(this IEnumerable<TItem> items,
            Func<TItem, Task<IEnumerable<TResult>>> func)
        {
            var progress = 0;

            var itemsList = new AsyncEnumerable<TResult>(async yield =>
            {
                foreach (var item in items)
                {
                    var dataItems = await func(item);
                    foreach (var data in dataItems)
                    {
                        await yield.ReturnAsync(data);
                    }

                    Interlocked.Increment(ref progress);
                }
            });

            return await Task.FromResult(itemsList);
        }
```

Usage of this is very simple:

```
var results = await items
                        .SelectAsync(async item =>
                        {
                            return await PerformWork(item);
                        });
```

**Comment by tyrotoxin** [comment]
> However if you have X async calls and each take Y ms then the total time will be X*Y ms.
That makes sense too me. Calling an `async` method (or any method that returns a `Task`) does not guarantee that it's executed on a separate thread - it can finish synchronously. The `AsyncEnumerable` merely helps to efficiently use threads from the thread pool by not blocking them.

If you want to optimize the time of one routine, you should use the `ParallelForEach`.

**Comment by Telavian** [comment]
That is correct. I will look into ParallelForEach.
Thanks.

**Comment by tyrotoxin** [comment]
Let me know if find any severe performance issues.
