### ISSUE TITLE
AggregateException throw during synchronous enumeration

### ISSUE THREAD

**Issue by TomPeters** [tyrotoxin/AsyncEnumerable#8]
In 1.4.2, this would throw an `Exception`:

```
new AsyncEnumerable<int>(async yield => { throw new Exception(); }).ToList();
```

While in 2.0.0, this throws an `AggregateException`:

```
new AsyncEnumerable<int>(async yield => { throw new Exception(); }).ToEnumerable().ToList();
```

I believe it is because calls to `Task.ConfigureAwait(false).GetAwaiter().GetResult()` were replaced with `.Result`. It would be better to replace it with `Task.GetAwaiter().GetResult()`, because then it would not wrap exceptions in `AggregateException`s

**Comment by tyrotoxin** [comment]
Man, stop misusing the library! :)
The fix is in v2.0.1
